resource: 'google_dialogflow_environment'
generation_type: 'mmv1'
api_service_name: 'dialogflow.googleapis.com'
api_version: 'v2beta1'
api_resource_type_kind: 'Environment'
fields:
  - field: 'agent_version'
  - field: 'description'
  - field: 'environmentid'
    provider_only: true
  - field: 'fulfillment.display_name'
  - field: 'fulfillment.features.type'
  - field: 'fulfillment.generic_web_service.password'
  - field: 'fulfillment.generic_web_service.request_headers'
  - field: 'fulfillment.generic_web_service.uri'
  - field: 'fulfillment.generic_web_service.username'
  - field: 'fulfillment.name'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'state'
  - field: 'text_to_speech_settings.enable_text_to_speech'
  - field: 'text_to_speech_settings.output_audio_encoding'
  - field: 'text_to_speech_settings.sample_rate_hertz'
  - field: 'text_to_speech_settings.synthesize_speech_configs.synthesize_speech_config.effects_profile_id'
  - field: 'text_to_speech_settings.synthesize_speech_configs.synthesize_speech_config.pitch'
  - field: 'text_to_speech_settings.synthesize_speech_configs.synthesize_speech_config.speaking_rate'
  - field: 'text_to_speech_settings.synthesize_speech_configs.synthesize_speech_config.voice.name'
  - field: 'text_to_speech_settings.synthesize_speech_configs.synthesize_speech_config.voice.ssml_gender'
  - field: 'text_to_speech_settings.synthesize_speech_configs.synthesize_speech_config.volume_gain_db'
